name: Test Sandbox
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  sandbox:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [21]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.15.4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test:sandbox:ci-with-ignore --fail-fast
