name: Deploy TypeDoc on GitHub pages

on:
    push:
      branches:
        main  

env:
  NODE_VERSION: 20.x.x
  ENTRY_FILE: 'packages'
  CONFIG_PATH: 'tsconfig.base.json'
  USES_PNPM: 'true'
  
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.15.0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run:  pnpm build

      - name: Build documentation
        run:  pnpm docs:generate

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
          clean: true